# Generated by Django 4.0.4 on 2022-06-12 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=255)),
                ('dep_address', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.IntegerField(default=0)),
                ('super_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephones.department', verbose_name='the related dep')),
            ],
            options={
                'ordering': ['dep_name'],
            },
        ),
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=255)),
                ('complete_number', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['extension'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(default='M', max_length=1)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(max_length=10, unique=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephones.department', verbose_name='the related dep')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephones.profile', verbose_name='the related profile')),
                ('position_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephones.positiontype', verbose_name='the related position type')),
            ],
            options={
                'ordering': ['position_type'],
            },
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephones.position', verbose_name='the related pos')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephones.profile', verbose_name='the related profile')),
                ('tel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephones.telephone', verbose_name='the related tel')),
            ],
            options={
                'ordering': ['tel'],
            },
        ),
    ]
