# Generated by Django 4.0.4 on 2022-06-13 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telephones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='super_dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telephones.department', verbose_name='the related dep'),
        ),
    ]
