# Generated by Django 4.0.4 on 2022-06-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephones', '0003_alter_profile_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dep_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
