# Generated by Django 4.0.4 on 2022-06-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephones', '0004_department_dep_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_title',
            field=models.CharField(blank=True, choices=[('معاونت', 'معاونت'), ('مدیریت', 'مدیریت'), ('گروه', 'گروه'), ('اداره', 'اداره'), ('دبیرخانه', 'دبیرخانه'), ('حوزه', 'حوزه'), ('مرکز', 'مرکز')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], default='M', max_length=1),
        ),
    ]
