# Generated by Django 4.0.4 on 2022-06-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephones', '0005_alter_department_dep_title_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='duties',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='dep_title',
            field=models.CharField(blank=True, choices=[('معاونت', 'معاونت'), ('مدیریت', 'مدیریت'), ('گروه', 'گروه'), ('اداره', 'اداره'), ('دبیرخانه', 'دبیرخانه'), ('حوزه', 'حوزه'), ('مرکز', 'مرکز'), ('کمیته', 'کمیته')], max_length=255, null=True),
        ),
    ]
