# Generated by Django 4.0.4 on 2022-06-19 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telephones', '0007_rename_dep_assign_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='telephones.profile', verbose_name='the related profile'),
        ),
        migrations.AlterField(
            model_name='assign',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='telephones.position', verbose_name='the related pos'),
        ),
        migrations.AlterField(
            model_name='assign',
            name='tel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tels', to='telephones.telephone', verbose_name='the related tel'),
        ),
    ]
