# Generated by Django 4.0.4 on 2022-06-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telephones', '0008_alter_assign_owner_alter_assign_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign',
            name='owner',
        ),
    ]
