# Generated by Django 4.0.4 on 2022-06-20 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telephones', '0009_remove_assign_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deps', to='telephones.department', verbose_name='the related dep'),
        ),
        migrations.AlterField(
            model_name='position',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='telephones.profile', verbose_name='the related profile'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_types', to='telephones.positiontype', verbose_name='the related position type'),
        ),
    ]
