# Generated by Django 4.0.4 on 2022-06-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephones', '0010_alter_position_dep_alter_position_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['dep_title', 'dep_name']},
        ),
        migrations.AlterField(
            model_name='department',
            name='dep_title',
            field=models.CharField(blank=True, choices=[('معاونت', 'معاونت'), ('مدیریت', 'مدیریت'), ('گروه', 'گروه'), ('اداره', 'اداره'), ('دبیرخانه', 'دبیرخانه'), ('حوزه', 'حوزه'), ('مرکز', 'مرکز'), ('کمیته', 'کمیته'), ('شورا', 'شورا')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='extension',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
