# Generated by Django 4.0.4 on 2022-08-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephones', '0011_alter_department_options_alter_department_dep_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['dep', 'position_type', 'owner']},
        ),
        migrations.AlterField(
            model_name='department',
            name='dep_title',
            field=models.CharField(blank=True, choices=[('معاونت', 'معاونت'), ('مدیریت', 'مدیریت'), ('دانشکده', 'دانشکده'), ('گروه', 'گروه'), ('اداره', 'اداره'), ('دبیرخانه', 'دبیرخانه'), ('حوزه', 'حوزه'), ('مرکز', 'مرکز'), ('کمیته', 'کمیته'), ('شورا', 'شورا'), ('سرای', 'سرای دانشجوی'), ('گیت', 'گیت')], max_length=255, null=True),
        ),
    ]
